project:
  type: website
  output-dir: docs

website:
  title: "Yutong"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - about.qmd
      - index1.qmd
      - insomnia.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

