---
title: "data cleaning"
author: "Wu Yutong"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#glimpse data
```{r, eval=TRUE, echo=TRUE}
library(tidyverse)
insomnia_uncleaned <-read.csv("insomnia.csv")
glimpse(insomnia_uncleaned) 
```

#selcting variables needed
```{r, eval=TRUE, echo=TRUE}
insomnia <- insomnia_uncleaned %>% # <-- pipe operator
   select(Group, SubGroup, Sex, Age, ISI_total, PSQI_total, BDI_total, ASHS_total, ASHS_physiological, ASHS_cognitive,ASHS_emotional, ASHS_SleepEnvirnmont, ASHS_DaytimeSleep, ASHS_substances, ASHS_bedtimeRoutine, ASHS_sleepStability, ASHS_BedroomSharing, DBAS_total, FIRST_total, GCTI_total, NEO_neuroticism, NEO_extraversion, NEO_openness, NEO_agreeableness, NEO_Conscientiousness, ACE_tot, asq_home, asq_school, asq_attendance, asq_romantic, asq_peer, asq_teacher, asq_future, asq_leisure, asq_finance, asq_responsibility, cope_disengage_su, cope_growth, cope_disengage_mental, cope_emotions, cope_socialsupp_instr, cope_active, cope_denial, cope_religion, cope_humor, cope_disengage_emo, cope_restraint, cope_socialsupp_emo, cope_acccept, cope_suppression, cope_planning)
 # View the columns stacked one below another
 glimpse(insomnia)
```

#data cleaning
```{r, eval=TRUE, echo=TRUE}
cleaned_insomnia <- na.omit(insomnia)

nrow(insomnia)
nrow(cleaned_insomnia)
```

#further grouping
```{r, eval=TRUE, echo=TRUE}
cleaned_insomnia$Sex <- factor(cleaned_insomnia$Sex, levels = c(0, 1), labels = c("Female", "Male"))

participants <- cleaned_insomnia %>%
  select(Group, SubGroup, Sex, Age)
glimpse(participants)

sleep_quality <- cleaned_insomnia %>%
  select(ISI_total, PSQI_total)
glimpse(sleep_quality)

causes <- cleaned_insomnia %>%
  select(BDI_total, ASHS_total, ASHS_physiological, ASHS_cognitive,ASHS_emotional, ASHS_SleepEnvirnmont, ASHS_DaytimeSleep, ASHS_substances, ASHS_bedtimeRoutine, ASHS_sleepStability, ASHS_BedroomSharing, DBAS_total, FIRST_total, GCTI_total, NEO_neuroticism, NEO_extraversion, NEO_openness, NEO_agreeableness, NEO_Conscientiousness, ACE_tot, asq_home, asq_school, asq_attendance, asq_romantic, asq_peer, asq_teacher, asq_future, asq_leisure, asq_finance, asq_responsibility)
glimpse(causes)

coping <- cleaned_insomnia %>%
  select(cope_disengage_su, cope_growth, cope_disengage_mental, cope_emotions, cope_socialsupp_instr, cope_active, cope_denial, cope_religion, cope_humor, cope_disengage_emo, cope_restraint, cope_socialsupp_emo, cope_acccept, cope_suppression, cope_planning)
glimpse(coping)
```

#graphs
##first question: how insomnia varies among age and sex
```{r, eval=TRUE, echo=TRUE}
ggplot(cleaned_insomnia, aes(x = Age, y = ISI_total)) +
  geom_line(aes(color = ISI_total), size = 1) +  # Customize point appearance
  labs(x = "Age", y = "Insomnia Severity") +
  ggtitle("Insomnia Severity by Age") +
  theme_minimal()

ggplot(cleaned_insomnia, aes(x = Sex, y = ISI_total)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(
    x = "Sex",
    y = "Insomnia Severity",
    title = "Insomnia Severity by Sex"
  )

```

#shiny
```{r, eval=TRUE, echo=TRUE}

```